### ISSUE TITLE
Revive

### ISSUE THREAD

**Issue by JoshMullins** [JoshMullins/MVPGadgets#37]
Still would like to get this project rolled out on SpigotMC. @TGRHavoc @pookeythekid

**Comment by pookeythekid** [comment]
I'll be totally honest... I haven't coded in four months or so because I lost interest in coding things that I'm not particularly motivated to make. I'm not sure when I'll get back to coding or for what kind of thing I'll get back into it for, but I've kind of dropped out of Minecraft plugins. I wish the best of luck to this project, and I hope it gets out there as a working and cool plugin.

**Comment by TGRHavoc** [comment]
Pull requests #39, #40 and #41 should solve this.. I hope 😛
